language: cpp
compiler:
  - gcc
  - clang
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq coinor-libcbc-dev coinor-libclp-dev coinor-libosi-dev coinor-libcgl-dev
before_script:
  - mkdir build
  - cd build
  - cmake .. 
script: 
  - make && ctest --output-on-failure

